# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('CompanyName', models.CharField(max_length=200)),
                ('CompanyProfile', models.TextField()),
                ('CompanyURL', models.CharField(max_length=200)),
                ('LastUpdate', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
                ('MobilePhnoe', models.CharField(max_length=200)),
                ('WangWangId', models.CharField(max_length=200)),
                ('Fax', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('MainProductService', models.CharField(max_length=200)),
                ('MainIndustry', models.CharField(max_length=200)),
                ('BusinessMode', models.CharField(max_length=200)),
                ('ServiceType', models.CharField(max_length=200)),
                ('OEMOrCustomService', models.CharField(max_length=200)),
                ('RegisterCapital', models.CharField(max_length=200)),
                ('FoundTime', models.CharField(max_length=200)),
                ('RegisterPlace', models.CharField(max_length=200)),
                ('CompanyType', models.CharField(max_length=200)),
                ('LegalRepresentative', models.CharField(max_length=200)),
                ('RegisterNo', models.CharField(max_length=200)),
                ('ProcessMethod', models.CharField(max_length=200)),
                ('IndustrialArt', models.CharField(max_length=200)),
                ('ManageCertification', models.CharField(max_length=200)),
                ('QualityCertification', models.CharField(max_length=200)),
                ('Warehouse', models.CharField(max_length=200)),
                ('EmpolyeeCount', models.CharField(max_length=200)),
                ('DeveloperCount', models.CharField(max_length=200)),
                ('PlantArea', models.CharField(max_length=200)),
                ('MainSalesRegion', models.CharField(max_length=200)),
                ('MainCustomerGroup', models.CharField(max_length=200)),
                ('ServiceField', models.CharField(max_length=200)),
                ('AgentLevel', models.CharField(max_length=200)),
                ('BrandName', models.CharField(max_length=200)),
                ('MonthlyProduction', models.CharField(max_length=200)),
                ('AnnualTurnover', models.CharField(max_length=200)),
                ('AnnualExport', models.CharField(max_length=200)),
                ('QualityControl', models.CharField(max_length=200)),
                ('BankOfDeposit', models.CharField(max_length=200)),
                ('Account', models.CharField(max_length=200)),
                ('HomePage', models.CharField(max_length=200)),
            ],
        ),
    ]
